### ISSUE TITLE
Kamilovy navrhy

### ISSUE THREAD

**Issue by shinedeveloper** [ZelenyMartin/uvod-do-linuxu#2]
Ahoj, koukal jsem se na tebou navrhovanou napln. Rozhodne dava smysl.
Mam predevsim dva body:
- Nechces uvazit zmenu nazvu z Uvodu do Linuxu na Uvod do Linuxu a prikazove radky? Ja treba Linux zdaleka nevnimam jako "ten s prikazovou radkou". Pouzivam Linux pres graficke prostredi stejne jako macOS nebo Windows. A pouzivam Android (coz je taky Linux) a prikazovou radku jsem tam pustil jednou a rychle ji zas zavrel.
- Chapu, ze ses rozhodl vyuzit WSL 2, protoze je to nejsnadnejsi na instalaci a je to takove pragmaticke reseni. Ale je otazka, jestli to pro studentky nebude matouci, ze prisly na kurz Linuxu a pracuji s Windows. Jakoze jestli jim to neda matouci pohled na situaci. Netvrdim, ze mam lepsi navrh, jak to udelat jinak, ale dokazu si predstavit cloudove Linuxy, VirtualBox nebo zapujcene pocitace.

**Comment by shinedeveloper** [comment]
Pozn: Mam dokonce nazor, ze shell (prikazova radka) je dobra tak akorat pro automatizaci (a na to jsou tak jako tak lepsi skriptovaci jazyky nez sh) a z interaktivniho pouzivani mela uz pred desitkami let zmizet. Ale respektuji, ze ji admini casto pouzivaji a je to tedy pro studentky prakticka znalost.
Nicmene rozumim, ze s tim nazorem jsem v mensine, tak ho nebudu nikomu vnucovat.

**Comment by vsevjednom-cz** [comment]
Za sebe souhlasím. Taky jsem chtěl holky hlavně naučit používat grafické rozhraní - prostě ukázat, že ho můžou mít fakt všude -, ale přizpůsobil jsem se informaci, že je budeme hlavně učit v bashi. Měli bychom jim bash ukázat, aby měly motivaci přijít znovu, ale jestli je to rovnou učit na první linuxové hodině, nevím. To by mohlo být až v nějaké následující pro pokročilé.

Na rozlousknutí, jak to nakonec bude, by to tu asi chtělo nějakou anketu.

Určitě bychom měli zmínit, že Android je taky linux. A souhlasím, že bash je vážně jen základ.

**Comment by ZelenyMartin** [comment]
@shinedeveloper díky za poznámky!
* Rád bych měl ten název krátký. Dost o příkazové řádce je v "lineupu". Mělo by to být ideálně pro vstupní znalosti "Mírně pokročilí"  (2 čtverečky ze 3). Ohledně grafického prostředí hlavně není žádné "výchozí" nebo jasně nejpoužívanější (Gnome 3?, KDE Plasma 5?, Xfce?, Mate?, Cinnamon?, LXDE?, LXQt?) - jaké byste chtěli ukazovat? To se učit nedá. Musí si to každý projít sám.
* **WSL2** opět hodně o tom je v lineupu a bude to vysvětleno. Alternativy se mi zatím moc nezdají:
  * Cloud - neodnese si "domů", složitější příprava
  * VirtualBox - to by zabralo celý půlden, možná víc. Bylo by to pro účastnice HW náročnější
  * Počítače z Czechitas - neodnesou si domů, složitější příprava
* Unix tady s námi bude brzy 50 let a ovládá se pořád stále stejně. Kdyby to byla taková bída, tak by to bezpochyby nemilosrdný tok času zazdil, ale když tady máme relativně nově i WSL (dříve to byl třeba Cygwin nebo MinGW) nebo nový Windows Terminal, tak bych řekl, že se od shellu minimálně neodkláníme. Samozřejmě máme kontejnery, Ansible, webové interface pro správu různých věcí, ale prostě ty základy linuxové příkazové řádky na úrovni jednodenního workshopu se určitě neztratí.
Určitě nechci učit žádné "programování v bashi". Zřetězení pár příkazů přes pipe do podoby užitečného "one-lineru" nepovažuju za skriptování.

@vsevjednom-cz Zatím by to byl formát jednodenního workshopu, což si myslím, že by mohlo absolventkám digitálních akademii a dlouhodobých kurzů, které jsou na prahu získání IT práce, mohlo stačit.

**Comment by shinedeveloper** [comment]
* Ja nechci ukazovat graficke rozhrani Linuxu. Myslim si, ze ucit praci s prikazovou radkou v Linuxu je v dnesni dobe stale prakticke, protoze se to pouziva. Jen rikam, ze Linux vnimam zcela jinak nez jen tu prehistorickou prikazovou radku. Proto jsem navrhoval presnejsi nazev kurzu s "prikazovou radkou".

* No a co se tyka toho, jestli je neco, co je tu s nami 50 let a pouziva se to, dobre nebo ne... Napriklad v Pakistanu, Afghanistanu a Indii je mnoho skol, kde se uci jen a pouze memorovat Koran v arabstine, ktere ani nerozumeji (protoze to ani nejsou Arabove). Pocet takto vzdelanych lidi mnohonasobne prevysuje pocet vsech ITaku (jen Pakistan ma pres 200 milionu lidi). Je to tu s nami tisice let. Osobne bych nedokazoval dobou pouzivani jestli je neco bida nebo ne :-) ... Ale zde je dulezite si uvedomit, ze vubec nerikam, ze to nemas v kurzu ucit. U tohoto bodu jsem jen prezentoval svuj nazor na danou technologii, jak taky vyrazne pisu vyse.

**Comment by ZelenyMartin** [comment]
Zavírám v rámci cleanup. Díky za podněty.
