### ISSUE TITLE
Návrhy ke zmínění

### ISSUE THREAD

**Issue by andywaltlova** [ZelenyMartin/uvod-do-linuxu#4]
Ahoj! 
přečetla jsem si konečně všechny materiály, Návrhů, co zmínit už tu ostatní dali několik, tak přidám co napadlo mě, a co mě zajímalo když jsem linux viděla poprvé.

- Určitě bych zmínila a ukázala použití workspaces - za mě obrovská výhoda pro lidi co často pracují na více věcech najednou.
- Zmínit, že prompt v terminálu lze customizovat, zdaleka nemusí vypadat u každého uživatele stejně - např. přidání informací o git repozitáři.
- vytváření aliasů
- `man` command (možná už si ho někde zmiňoval)
- nejen šipka nahoru a dolu v terminálu, ale i vyhledávání v historii (ať už s grep nebo ctrl+r)

**Comment by vsevjednom-cz** [comment]
Ahoj, trochu ti do toho vstoupím. To, co tu napíšu, souvisí s tím, cos tu napsala ty. Neber to prosím nijak zle, není to nic proti tobě, jen ses tu nechtěně trefila do věci, která tu zmíněna ještě nebyla. Myslím, že by pro holky bylo jednodušší, kdyby nemusely přemýšlet nad anglickými slůvky 🙃.

Při čtení mě hned napadaly tyto myšlenky:
Workspaces - co to? No asi tuším...
Prompt - co to je?
Customizovat - to vím, co znamená, ale čeština to slovo má taky...
Command taky vím, ale...

Používejme prosím při výuce primárně češtinu. Anglický název samozřejmě použijme taky, ale vysvětleme holkám, co to slovo znamená. Výraz customizovat nepoužívejme vůbec, prosím. Když to řekneme česky, bude to snáze pochopitelné.

🙃

**Comment by andywaltlova** [comment]
Ahoj, já to tu píšu jako návrh pro martina :) určitě to nebylo myšleno tak, aby to říkal přesně jako píšu. 

Každopádně je dobré, že to zmiňuješ, při ostatní výuce, kterou martin má například na DA, je zvyklostí termíny vysvětlovat, nepřišlo mi nutné to nějak zdůrazňovat. Připomenout to ale každopádně neuškodí. 👍

**Comment by ZelenyMartin** [comment]
Díky moc za komentáře!

@andywaltlova:
* workspaces - workshop by byl primárně na příkazovou řádku. Různé grafické prostředí, bych asi jen ukázal jako screenshoty na webu
* prompt - zmínil bych, že v různých distribucích může být prompt nastaven jinak, ale víc bych do toho nezabíral. Přeci jen, je to pořád jen jednodenní workshop
* aliasy - asi mi nezbude jinak než to zmínit, ale jen okrajově. Neviděl bych zatím jako kritické to dávat do textu. Ještě uvidím.
* `man` tam bude
* `history | grep` tam bude. Ctrl+r je z mého pohledu trochu nepřehledné a není ideální pro začátečníky.

@vsevjednom-cz:
* anglicismy - částečně souhlasím, částečně ne. Vždy se snažím nepoužívat zbytečně anglicismy, pokud existuje ustálený překlad (_příkaz_, _příkazová řádka_). Ale např. _prompt_ podle mě nemá český ekvivalent. Ale je dost možné, že mi někdy něco ujede.

**Comment by vsevjednom-cz** [comment]
Je slovem prompt myšleno české slovo promptní? Pokud ano, synonymem je slovo okamžitý nebo pohotový. Asi bych se nebál použít ani slovo rychlý. Slovo promptní bude asi pro spoustu lidí neznámé.

**Comment by zakjakub** [comment]
> Je slovem prompt myšleno české slovo promptní? Pokud ano, synonymem je slovo okamžitý nebo pohotový. Asi bych se nebál použít ani slovo rychlý. Slovo promptní bude asi pro spoustu lidí neznámé.

`Prompt` je jeden řádek z tohoto:
![image](https://user-images.githubusercontent.com/16374701/110605497-7c3ff100-8189-11eb-8313-25a14cc92221.png)

Žádný český krátký ekvivalent mě také nenapadá (minimálně ne nic, co by se běžně používalo).

Co se týče anglicismů, tak jsou v mnohých případech potřeba, ačkoliv to pro začátečníka může vypadat zvláštně a zmatečně - když bude něco hledat, tak s českým označením, zvlášť pokud není nějak extrémně rozšířené, moc nepochodí...

**Comment by vsevjednom-cz** [comment]
Aha, tak to nevím ani obecně, jak bych pojmenoval. Ohledně dohledávání souhlasím, že je třeba v drtivé většině případů znát anglický výraz. Vypadá to, že všichni víte, jak v tom při učení nalézt rovnováhu, takže v pořádku 🙃.

**Comment by ZelenyMartin** [comment]
Zavírám v rámci cleanup. Díky za podněty.
